[core]
name: T2factory

displayText:Т2 завод техники
displayDescription: Т2 завод наземной техники

price: 2000
class: CustomUnitMetadata
maxHp: 1100
mass: 9000
radius: 38

isBuilding: true

techLevel: 2
buildSpeed: 20s

exit_x:0
exit_y:20

tags: T2Factory

#footprint used for collisions with units (left, up, right, down)
footprint: -1, -1, 1, 1

#used for placement, and placement of other buildings
constructionFootprint: -1,-1,1,1

canBuild_1_name: setRally
canBuild_1_pos:  1

copyFrom: ROOT:buildings/factory/T1/land_T1factory/T1_factory.ini

[canBuild_T2]
pos:2
name: строитель, жук, T2_air_defense, virus_artelery, вирус_танк, T2_virus_tesla_tank, virus_plasma_tank, duster, oreshnik, тяжелый_танк

#[action_upgrade] 
#convertTo: 
#iconImage: ROOT:icons/improve.png
#displayType: Upgrade
#price: 1000
#buildSpeed: 20s
#text: Т2
#description: Позволяет создавать юнитов второго класса.
#pos: -1

[graphics]
image: T2_factory.png

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority: 0.034
ai_upgradePriority: 0.7
noneInBaseExtraPriority: 0.08
noneGlobalExtraPriority: 0.1
maxEachBase: 1
maxGlobal: 5