[core]
name: тяжелый_танк
displayText: сверх тяжелый танк

showInEditor: true
class: CustomUnitMetadata
price: 2000
maxHp: 3500
mass: 50000
transportSlotsNeeded: 4

techLevel: 2
buildSpeed: 20s

radius: 41
displayRadius: 30

isBio: true

[graphics]
#total_frames: 3

image: body.png
#image_wreak: dead_body.png

image_shadow: AUTO
#animation_moving_start: 0
#animation_moving_end: 2
#animation_moving_speed: 2


dustEffect: true

[turret_1]
x: 0
y: 0

image: turret.png

[turret_2]
x: 0
y: 0
attachedTo: 1

image: mini_turret.png

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true

turretSize: 21
turretTurnSpeed: 3

maxAttackRange: 210
shootDelay: 25

[movement]
movementType: LAND
moveSpeed: 0.35
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

reverseSpeedPercentage: 0.3

maxTurnSpeed: 2
turnAcceleration: 0.2

moveSlidingMode :false
moveIgnoringBody:false
