[core]
name: тяжелый_танк
displayText: сверх тяжелый танк

showInEditor: true
class: CustomUnitMetadata
price: 3500
maxHp: 4000
mass: 50000
transportSlotsNeeded: 4

techLevel: 2
buildSpeed: 25s

radius: 41
displayRadius: 30
armour: 15

isBio: true

[graphics]
total_frames: 5

image: body.png
#image_wreak: dead_body.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 4
animation_moving_speed: 5

dustEffect: true


[turret_1]
x: 3
y: 17
#image_drawOffsetX: 5
image_drawOffsetY: 5

delay: 100
projectile: big
image: turret.png
aimOffsetSpread: 0.05

[turret_2]
x: 4
y: -8
attachedTo:1
#image_drawOffsetX: 7
#image_drawOffsetY: 20

projectile: pulimet
aimOffsetSpread: 0.07

image: mini_turret.png

[projectile_big]
areaDamage: 150 
areaRadius: 40

life: 150
frame: 3
explodeEffect: explore_b

[projectile_pulimet]
directDamage: 10

life: 100
frame: 1

[effect_explore_b]
image: ROOT:/effect/fire.png

total_frames: 4
animateFrameStart: 0 
animateFrameSpeed: 3
animateFrameEnd: 3

life: 300

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 21
turretTurnSpeed: 1

maxAttackRange: 210
shootDelay: 25

[movement]
movementType: LAND
moveSpeed: 0.35
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

reverseSpeedPercentage: 0.3

maxTurnSpeed: 2
turnAcceleration: 0.2

moveSlidingMode :false
moveIgnoringBody:false
