[core]
name: жук

displayDescription: жучара

price: 3000 
radius: 20 
maxHp:3500
armour: 8
mass: 9000 
isBio: true 

[graphics]
#lock_body_rotation_with_main_turret: true
splastEffect: true
image: bug.png
image_turret: heat.png

[turret_1]
x: 0
y: 15
canAttackMaxAngle: 0

[arm_1]
x: -6
y: 17
drawDirOffset: 7
image_end: arm_l.png 
  
[arm_2]
x: 6
y: 17
drawDirOffset: -7
image_end: arm_p.png 

[attack]
isMelee: true

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

isFixedFiring: true

turretSize: 35
turretTurnSpeed: 1

maxAttackRange: 15
shootDelay: 50

[leg_1]
x: -8
y: 11
attach_x: -1
attach_y: 8
moveSpeed: 2.6

heightSpeed: 2
moveWarmUp: 3

resetAngle:10

holdDisMin_maxMovingLegs: 6 
holdDisMin: 1
holdDisMax: 2


image_leg: leg_l.png
image_foot: foot.png
estimatingPositionMultiplier: 0.6

[leg_2]
@copyFromSection: leg_1
image_leg: leg_p.png
x: 8
y: 11
attach_x: 1
attach_y: 8
estimatingPositionMultiplier: 0.6

[leg_3]
@copyFromSection: leg_1
image_leg: leg_l.png
x: -10
y: -10
attach_x: -1
attach_y: -5
estimatingPositionMultiplier: 0.6

[leg_4]
@copyFromSection: leg_1
image_leg: leg_p.png
x: 10
y: -10
attach_x: 3
attach_y: -6
estimatingPositionMultiplier: 0.6

[leg_5]
@copyFromSection: leg_1
image_leg: leg_p.png
x: 8
y: -1
attach_x: -25
attach_y: -15

[leg_6]
@copyFromSection: leg_1
image_leg: leg_l.png
x: -11
y: -1
attach_x: 2
attach_y: -6



[movement]
movementType: OVER_CLIFF

moveSpeed: 0.65
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 3
turnAcceleration: 0.2

reverseSpeedPercentage: 1

moveSlidingMode :false
moveIgnoringBody:false