[core]
name: ptur 
displayText: птур
displayDescription: птуровозка мало ХП и дольгая перезарядка но это компенсируеться малой ценой и хорошим уроном 

mass: 5000 
price: 800 
maxHp: 200 
transportSlotsNeeded: 1

techLevel: 1
buildSpeed: 10s

radius: 10 
displayRadius: 10
isBio: true

[graphics]
total_frames: 2

image: body.png
image_wreak: dead_body.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 2

dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 7
turretTurnSpeed: 4

maxAttackRange: 180
shootDelay: 5s

[turret_1]
x: 0
y: 0

projectile: 1
#barrelX: 0
#barrelY: 0
aimOffsetSpread: 0

image: turret.png

[projectile_1]
directDamage: 250
image: roket.png
life: 250
armourIgnoreAmount: 3

speed: 2
targetSpeedAcceleration: 0.4
targetSpeed: 3.7
trailEffect: roket_flame

[effect_roket_flame]
image: ROOT:/effect/miniature_roket_fire_8_frme.png

xOffsetRelative: -2
yOffsetRelative: -9

total_frames: 8
animateFrameStart: 0 
animateFrameSpeed: 1
animateFrameEnd: 7

[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.2

reverseSpeedPercentage: 0.5

maxTurnSpeed: 5
turnAcceleration: 0.25

moveSlidingMode :false
moveIgnoringBody:false