[core]
name: NEW_air_defense
displayText: ПВО установка

showInEditor: true
class: CustomUnitMetadata
price: 900
maxHp: 700
mass: 1900
transportSlotsNeeded: 1

techLevel: 1
buildSpeed: 8s

radius: 10 
displayRadius: 11

energyMax: 5
energyRegen: 0.015
energyNeedsToRechargeToFull: true

[graphics]
total_frames: 3

image: body.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 2

dustEffect: true

#scaleTurretImagesTo: 14

[turret_1]
x: 0
y: -5
image: turret.png

barrelX: 0
barrelY: 5

projectile: 1

shoot_sound: missile_fire
shoot_sound_vol: 0.2
shoot_flame: small
shoot_light: #FFEECCCC

recoilOffset: -0.3
recoilOutTime: 4
recoilReturnTime: 15
energyUsage: 1

[projectile_1]
directDamage: 40
image: ROOT:effect/P_PointyRocket.png

life: 240
speed: 0.5
targetSpeed: 6
trailEffectRate: 3
largeHitEffect: true

autoTargetingOnDeadTarget: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
turretSize: 13

turretTurnSpeed: 4

maxAttackRange: 145
shootDelay: 22

[movement]
movementType: LAND
moveSpeed: 0.80
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

reverseSpeedPercentage: 0.5

maxTurnSpeed: 5
turnAcceleration: 0.25

moveSlidingMode :false
moveIgnoringBody:false