[core]
name: жук

displayDescription: жучара

price: 3000
radius: 17
maxHp:3500
armour: 8
mass: 9000
isBio: true

[graphics]
lock_body_rotation_with_main_turret: true
splastEffect: true
image: bug.png
image_turret: heat.png

[projectile_1]
image: foot.png

areaDamage: 40
areaRadius: 50
life: 60

deflectionPower: 0

instant: true
shieldDamageMultiplier: 0
shieldDefectionMultiplier: 0
armourIgnoreAmount: 1

[turret_1]
x: 0
y: 15
projectile: 1
idleDir: 10
#dleDirReversing: 0


[arm_1]
x: -6
y: 15
drawDirOffset: 7
image_end: arm_l.png

[arm_2]
x: 6
y: 15
drawDirOffset: -7
image_end: arm_p.png

[attack]
isMelee: true
meleeEngangementDistance: 60
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true

turretSize: 20
turretTurnSpeed: 0

maxAttackRange: 20
shootDelay: 40

[leg_1]
x: -8
y: 11
attach_x: -1
attach_y: 8
moveSpeed: 2.6

heightSpeed: 2
moveWarmUp: 3

resetAngle:10

holdDisMin_maxMovingLegs: 6
holdDisMin: 1
holdDisMax: 2


image_leg: leg_l.png
image_foot: foot.png
estimatingPositionMultiplier: 0.6

[leg_2]
@copyFromSection: leg_1
image_leg: leg_p.png
x: 8
y: 11
attach_x: 1
attach_y: 8
estimatingPositionMultiplier: 0.6

[leg_3]
@copyFromSection: leg_1
image_leg: leg_l.png
x: -10
y: -10
attach_x: -1
attach_y: -5
estimatingPositionMultiplier: 0.6

[leg_4]
@copyFromSection: leg_1
image_leg: leg_p.png
x: 10
y: -10
attach_x: 3
attach_y: -6
estimatingPositionMultiplier: 0.6

[leg_5]
@copyFromSection: leg_1
image_leg: leg_p.png
x: 8
y: -1
attach_x: -25
attach_y: -15

[leg_6]
@copyFromSection: leg_1
image_leg: leg_l.png
x: -11
y: -1
attach_x: 2
attach_y: -6


[animation_attackClaw]
onActions: attack
#blendIn: 0.5s
#blendOut: 0.5s
#KeyframeTimeScale: 0.15
arm1_0.4s: {x:-1, y:3, height:1, dir:-10}
arm1_0.5s: {x:-1, y:5, height:2, dir:-10}
arm1_0.65s: {x:-2, y:3, height:3, dir: 14}
arm1_0.84s: {x:0, y:0, height:0, dir: 14}

arm2_0.4s: {x:1, y:3, height:1, dir:10}
arm2_0.5s: {x:1, y:5, height:2, dir:10}
arm2_0.65s: {x:2, y:3, height:3, dir:-14}
arm2_0.84s: {x:0, y:0, height:0, dir:-14}

#arm2_0.4s: {x:10, y:5, height:5, dir:10}
#arm2_0.5s: {x:10, y:10, height:5, dir:10}
#arm2_0.65s: {x:2, y:15, height:5, dir:-14}
#arm2_0.84s: {x:2, y:7, height:5, dir:-14}
#arm2_1s: {x:2, y:0, height:5, dir:-14}
#arm2_1.2s: {x:0, y:0, height:0, dir:0}

[action_test]
buildSpeed: 0s
text: test
playAnimation: attackClaw

[action_STAT]
isVisible: false
buildSpeed: 0s
text: test
setUnitStats: moveSpeed= 5

[action_STAT2]
buildSpeed: 0s
text: test2
isVisible: false
setUnitStats: maxAttackRange = 600

[movement]
movementType: OVER_CLIFF

moveSpeed: 0.65
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 3
turnAcceleration: 0.2

reverseSpeedPercentage: 0

moveSlidingMode :false
moveIgnoringBody:false
