[core]
name: turret_T2
displayText: T2 turret
displayText_ru: Т2 турель

class: CustomUnitMetadata
price: 900
maxHp: 1050
mass: 1000

#used for placement, and placement of other buildings
constructionFootprint: -1, -1, 1, 1

techLevel: 1
buildSpeed: 17s

radius: 20
isBio: true

isBuilding: true

tags: T1turret

[graphics]
image: ROOT:buildings/turret/base/turret_base.png
image_wreak: ROOT:buildings/turret/base/ahahah_sdohla.png

[turret_0]
x:0
y:5
canAttack: false
image:turret.png

[turret_cannon1]
x: 0
y: 0
attachedTo: 0
slave: true

image_drawOffsetX: -3
image_drawOffsetY: 9

barrelX: -2
barrelY: 11

image: ROOT:buildings/turret/base/cannon.png

recoilOffset: -2
recoilOutTime: 5
recoilReturnTime: 5

[turret_cannon2]
x: 0
y: 0
attachedTo: 0
slave: true

image_drawOffsetX: 4
image_drawOffsetY: 9

barrelX: -2
barrelY: 11

image: ROOT:buildings/turret/base/cannon.png

recoilOffset: -2
recoilOutTime: 5
recoilReturnTime: 5

[projectile_1]
directDamage: 35
life: 70
speed: 6.5
frame: 2

drawSize: 0.8

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretTurnSpeed: 2

maxAttackRange: 180

shootDelay: 60

[movement]
movementType: NONE
moveSpeed: 0

[ai]
buildPriority: 0.47
noneInBaseExtraPriority: 0.35

recommendedInEachBaseNum: 2
maxEachBase: 4
recommendedInEachBasePriorityIfUnmet: 0.7