[core]
name: air_defense
displayText: ПВО установка

showInEditor: true
class: CustomUnitMetadata
price: 900
maxHp: 700
mass: 1900
transportSlotsNeeded: 1

techLevel: 1
buildSpeed: 8s

radius: 10 
displayRadius: 11

energyMax: 5
energyRegen: 0.015
energyNeedsToRechargeToFull: true
isBio: true

[graphics]
total_frames: 4

image: body.png
image_wreak: dead_body.png
image_turret: anti_air_flare_gun.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 2

dustEffect: true

scaleTurretImagesTo: 14

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
turretSize: 13

turretTurnSpeed: 4

maxAttackRange: 130
shootDelay: 20

[turret_1]
x: 0
y: -5
image: anti_air_flare_gun.png

barrelX: 0
barrelY: 5

#canAttackCondition: if not self.energy(lessThan=5)
#invisible: if self.energy(lessThan=5)

projectile: 1

shoot_sound: missile_fire
shoot_sound_vol: 0.2
shoot_flame: small
shoot_light: #FFEECCCC

recoilOffset: -0.2
recoilOutTime: 4
recoilReturnTime: 15
energyUsage: 1

#[turret_2]
#x: 0
#y: 0
#copyFrom: 1 
#attachedTo: 1

#barrelX: -2
#barrelY: 5
#canAttackCondition: if not self.energy(lessThan=4)
#invisible: if self.energy(lessThan=4)
#linkDelayWithTurret: 1 


[projectile_1]
directDamage: 40
life: 240
speed: 0.5
targetSpeed: 6
trailEffectRate: 3
largeHitEffect: true
#ballistic: true
#ballistic_delaymove_height:0
#ballistic_height: 4
frame: 4

autoTargetingOnDeadTarget: true

[movement]
movementType: LAND
moveSpeed: 0.80
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

reverseSpeedPercentage: 0.5

maxTurnSpeed: 5
turnAcceleration: 0.25

moveSlidingMode :false
moveIgnoringBody:false