[core]
name: строитель
displayText: Тех. строитель
displayDescription: -продвинутый строитель строитель\n-имеет малое самовосстановление\n-может чинить юнитов

showInEditor: true
class: CustomUnitMetadata
price: 1900
maxHp: 1000
mass: 1000

techLevel: 2
buildSpeed: 15s

canRepairBuildings: true
canRepairUnits: true

nanoRange: 95
nanoBuildSpeed: 2.0
nanoRepairSpeed: 0.3

tags: builder, T2

radius: 20
displayRadius: 21

isBio: true

selfRegenRate: 0.01

#общий патерн строений для всех строителей
copyFrom: ROOT:RAI/building_list.template

[graphics]
#image_shadow: AUTO
image: body.png
image_turret: turret.png

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[canBuild_build_logic_T2]
forceNano: true
name: T2factory
isLocked: if not numberOfUnitsInTeam(lessThan=65, withTag='T2Factory', incompleteBuildings=true) and self.isControlledByAI()
pos:  3

[turret_1]
#nano turret 
x: 2
y: 13

barrelX: 0
barrelY: 14

[effect_builds]
image: ROOT:effect/builder_charge.png

fadeInTime: 2
fadeOut: 1 

life: 300

[leg_1]
x: -8
y: 11
attach_x: 6
attach_y: 8
moveSpeed: 4

heightSpeed: 10
moveWarmUp: 5

resetAngle: 20

holdDisMin_maxMovingLegs: 2
holdDisMin: 2
holdDisMax: 5

hardLimit: 30

image_leg: leg1.png
image_foot: foot.png

estimatingPositionMultiplier: 0.4

[leg_2]
@copyFromSection: leg_1
image_leg: leg2.png

x: 8
y: 11
attach_x: -6
attach_y: 8


[leg_3]
@copyFromSection: leg_1

x: -10
y: -10
attach_x: 6
attach_y: -4

[leg_4]
@copyFromSection: leg_1

x: 10
y: -10
attach_x: -6
attach_y: -4


[leg_5]
@copyFromSection: leg_1
image_leg: leg2.png

x: 8
y: -1
attach_x: -6
attach_y: -1


[leg_6]
@copyFromSection: leg_1
x: -8
y: -1
attach_x: 6
attach_y: -1


[movement]
movementType: OVER_CLIFF

moveSpeed: 0.65
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 3
turnAcceleration: 0.2

reverseSpeedPercentage: 0.5

moveSlidingMode :false
moveIgnoringBody:false

[ai]
useAsBuilder: true
maxGlobal: 6