[core]
name: pulsar
displayText: Пульсар
class: CustomUnitMetadata

price: 700 
mass: 1000 
maxHp: 300 

radius: 16
displayRadius: 16

techLevel: 1
buildSpeed: 10s

isBio: true

[graphics]
total_frames: 3
image: body.png
image_shadow: AUTO

animation_idle_start: 0
animation_idle_end: 2
animation_idle_speed: 4
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 4

dustEffect: false
lock_body_rotation_with_main_turret: true

[turret_1]
x:0
y:0
projectile: 1
barrelX: 0
barrelY: 5

[projectile_1]
directDamage: 50
image: ROOT:icons/nah_projectile.png
life: 90
speed: 0.5
targetSpeed: 6
#trailEffectRate: 3
trailEffect: proj_frame

[effect_proj_frame]
life: 90
#fadeOut: true
image: P_Bullet.png

alpha: 1
#fadeinTime: 1 
drawUnderUnits: false 

total_frames: 3
animateFrameStart: 0 
animateFrameSpeed: 1 
animateFrameEnd: 2

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
maxAttackRange: 150
shootDelay: 80

[movement]
movementType: AIR
moveSpeed: 1.5
moveAccelerationSpeed: 2
moveDecelerationSpeed: 2
reverseSpeedPercentage: 0.3