[core]
name: BuildBot
displayText: Механ. Строитель
displayDescription: строит

showInEditor: true
class: CustomUnitMetadata
price: 700
maxHp: 500
mass: 1000

techLevel: 1
buildSpeed: 15s

canRepairBuildings: true
canRepairUnits : false

nanoRange: 95
nanoBuildSpeed: 2.0
nanoRepairSpeed: 0.3

tags: AiBuilder

radius: 30
displayRadius: 20

isBio: true

[graphics]
image_shadow: AUTO
image: build1.png
image_turret: NONE

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[canBuild_Reclaim]
name: reclaim
pos:  -1

[canBuild_T1_build]
forceNano: true
name: T1factory, RAIextractor, fabricatorT1_m
pos:  1

[canBuild_T1_cocon]
forceNano: true
name: T1coc
isLocked: if self.isControlledByAI

[turret_1]
#nano turret
x: 2
y: 13

canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false

[leg_1]
x: -8
y: 11
attach_x: -20
attach_y: 17
moveSpeed: 4

image_leg: leg11.png
image_foot: foot1.png

heightSpeed: 3
moveWarmUp: 3

resetAngle:12

holdDisMin_maxMovingLegs: 4
holdDisMin: 1
holdDisMax: 3

estimatingPositionMultiplier: 0.2

[leg_2]
@copyFromSection: leg_1
x: 8
y: 11
attach_x: 20
attach_y: 17
estimatingPositionMultiplier: 0.2 

[leg_3]
@copyFromSection: leg_1
x: -10
y: -15
attach_x: -20
attach_y: -20
estimatingPositionMultiplier: 0.2

[leg_4]
@copyFromSection: leg_1
x: 10
y: -15
attach_x: 20
attach_y: -20
estimatingPositionMultiplier: 0.2


[movement]
movementType: OVER_CLIFF

moveSpeed: 1
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 3
turnAcceleration: 0.2

reverseSpeedPercentage: 0.4

moveSlidingMode :false
moveIgnoringBody:false

[ai]
useAsBuilder: true
maxGlobal: 12
