[core]
name: light_turret
displayText: light turret
displayText_ru: легкая турель

class: CustomUnitMetadata
price: 400
maxHp: 350
mass: 1000

#used for placement, and placement of other buildings
constructionFootprint: -1, -1, 1, 1

techLevel: 1
buildSpeed: 15s

radius: 18
isBio: true

isBuilding: true

tags: T1turret

energyMax: 2
energyRegen: 0.02
energyNeedsToRechargeToFull: true

[graphics]
image: ROOT:buildings/turret/base/turret_base.png
image_wreak: ROOT:buildings/turret/base/ahahah_sdohla.png

imageScale: 0.9
showEnergyBar: false

[turret_0]
x:0
y:5
canAttack: false
image:turret.png

[turret_1]
x:0
y:5
attachedTo: 0
slave: true

image_drawOffsetX: 0
image_drawOffsetY: 5

barrelX: 0
barrelY: 6

image: ROOT:buildings/turret/base/cannon.png
energyUsage: 1

recoilOffset: -1
recoilOutTime: 2
recoilReturnTime: 4

[projectile_1]
directDamage: 15
life: 60
speed: 6
frame: 1

drawSize: 0.8

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretTurnSpeed: 2

maxAttackRange: 162

shootDelay: 10

[movement]
movementType: NONE
moveSpeed: 0

[ai]
buildPriority: 0.47
noneInBaseExtraPriority: 0.35

recommendedInEachBaseNum: 2
maxEachBase: 4
recommendedInEachBasePriorityIfUnmet: 0.7