[core]
name: virus_flamethower
displayText: вирусный огемет

mass: 4000 
showInEditor: true
class: CustomUnitMetadata
price: 750
maxHp: 250

techLevel: 1

transportSlotsNeeded: 1

buildSpeed: 10s

radius: 15
displayRadius: 15

[graphics]
total_frames: 4

image: body.png
image_wreak: dead_body.png
image_turret: turret.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 2

dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 12
turretTurnSpeed: 8
maxAttackRange: 120
shootDelay: 4.5

[turret_1]
#flame barrel
x: 0
y: 0
attachedTo: 2
slave: true
invisible: false

image: turret.png
projectile: 1

turnSpeed: 0
turnSpeedAcceleration: 1.0

canShoot: true

shoot_sound: buiding_explode
shoot_sound_vol: 0.075
shoot_light: #AAffb237

size: 4.5

#recoilOffset: -1
#recoilOutTime: 4
#recoilReturnTime: 3


[turret_2]
#turret
x: 0
y: 3.5

canShoot: false

#recoilOffset: -0.25
#recoilOutTime: 4
#recoilReturnTime: 3


[projectile_1]
#flame thrower

life: 70
speed: 5
speedSpread: 1

frame: 3
drawSize: 1.1

flameWeapon: true
hitSound: false

targetGround:true
targetGroundSpread: 20

deflectionPower: -1

areaDamage: 5
areaRadius: 65

lightColor: #e24a0e
lightSize: 0.6

buildingDamageMultiplier: 0.5
shieldDamageMultiplier: 0.75

tags: inflictFire

[movement]
movementType: LAND
moveSpeed: 1.1
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.06

reverseSpeedPercentage: 0.5

maxTurnSpeed: 2.1
turnAcceleration: 0.25

moveSlidingMode :false
moveIgnoringBody:false
