[core]
name: building_RAIcommandCenter
isUnselectable: true

showInEditor: false
class: CustomUnitMetadata
price: 1
maxHp: 1
mass: 1
transportSlotsNeeded: 0

techLevel: 1
buildSpeed: 00.1

radius: 55
displayRadius: 13

energyMax: 600
energyRegen: 1

[canBuild_0]
name: строитель_доходяга 
isVisible: false

[graphics]
total_frames:1
image_shadow: NONE
#Активировать их когда готово
#animation_idle_start: 0
#animation_idle_end: 59
#animation_idle_speed: 6
image: GBaseballShadow1.png
showEnergyBar: false

[attack]
canAttack: false
[movement]
movementType: NONE
