[core]
name: selector
displayText_ru: Селектор
displayText: selector

price: 500
maxHp: 2000
mass: 10000
radius: 16

isPickableStartingUnit: true
overrideAndReplace: commandCenter

isBuilding: true

[canBuild_0]
name: строитель_доходяга
isVisible: false

[action_RAI]
@define pr: 1
text: RAI
# iconImage:
convertTo: RAI_main_base
buildSpeed: 6s
#спавним юнита коий проигрывает анимцию создания шаба
whenBuilding_temporarilyConvertTo: building_RAIcommandCenter
spawnUnits: goo
attachments_addNewUnits: goo

[hiddenAction_random]
autoTrigger: if rnd(0, 0) >= 0 and self.isControlledByAI()
alsoQueueAction: RAI

#[action_vanil]
#text: ванила
# iconImage:
#convertTo: commandCenter_fake
#buildSpeed: 6s
#whenBuilding_temporarilyConvertTo: building_commandCenter

[graphics]
image: selector.png

[movement]
movementType: NONE

[attack]
canAttack:false
