[core]
name: selector
displayText_ru: Селектор
displayText: selector

price: 500
maxHp: 2000
mass: 10000
radius: 16

isPickableStartingUnit: true
overrideAndReplace: commandCenter

isBuilding: true

tags: selector

autoTriggerCooldownTime: 1s

[canBuild_0]
name: строитель_доходяга
isVisible: false

#---------------------------
# занятые логикой флаги: 25
# индификатор синих жуков: 1

#---------------------------

# шаблон кода переключения фракций
[hiddenAction_shablon]
buildSpeed: 0
showMessageToAllPlayers: %{self.playerName} Chose a faction
showMessageToAllPlayers_ru: %{self.playerName} Выбрал фракцию
resetCustomTimer: true

# мерцающая обводка
isGuiBlinking: if self.hasFlag(id=${fraction_index})
isLocked: if self.hasFlag(id=${fraction_index})
# для нажатия 1 раз
allowMultipleInQueue: false
alwaysSinglePress: true

# добовляем тег-маркер готовности
temporarilyAddTags: ready

# активриуем флаг созласно индификатору для понимания какая фракция выбрана
addResources: setFlag=${fraction_index}

[action_RAI]
@copyFromSection: hiddenAction_shablon

# задаем индекс определяющий фракцию как индификатор для шаблонной логики
@global fraction_index: 1
text: RAI
iconImage: bases/RAi_base/GBaseballShadow.png

[action_cancel]
text: cancel
text_ru: отмена

description: %{self.customTimer()}
showMessageToAllPlayers: %{self.playerName} canceled the choice of faction
showMessageToAllPlayers_ru: %{self.playerName} отменил выбор

# убираем тег-маркер для того что бы покозать что кто то не готов
temporarilyRemoveTags: ready

buildSpeed: 0
# выключаем флаг выбраной фракции
addResources: unsetFlag=${fraction_index}

resetCustomTimer: true

[hiddenAction_convert_to_RAI]
autoTrigger: if self.hasFlag(id=1) and self.customTimer() > 11 and numberOfUnitsInAllTeams(withTag="selector") == numberOfUnitsInAllTeams(withTag="ready")

showMessageToPlayer: В бой !

#buildSpeed: 10s
convertTo: RAI_main_base
#спавним юнита коий проигрывает анимцию создания шаба
whenBuilding_temporarilyConvertTo: building_RAIcommandCenter
spawnUnits: goo
attachments_addNewUnits: goo

# обратный отсчет
[hiddenAction_starts]
autoTrigger: if self.customTimer() > 0 and self.hasFlag(id=${fraction_index}) and self.customTimer() <= 11 and numberOfUnitsInAllTeams(withTag="selector") == numberOfUnitsInAllTeams(withTag="ready")

showMessageToPlayer: %{int(self.customTimer())}

# сбрасываем таймер для синхронищации отсчета вообе у всех
[hiddenAction_rest_timer]
autoTrigger: if numberOfUnitsInAllTeams(withTag="selector") == numberOfUnitsInAllTeams(withTag="ready") and not self.hasFlag(id=25)
resetCustomTimer: true

addResources: setFlag = 25

# выбор случайной фракции
[hiddenAction_random]
autoTrigger: if rnd(0, 0) >= 0 and self.isControlledByAI() and not self.hasFlag(id=${fraction_index})
alsoQueueAction: RAI

[graphics]
image: selector.png

image_offsetY: -10
image_offsetX: 1

[movement]
movementType: NONE

[attack]
canAttack:false
