[core]
name: selector
displayText_ru: Селектор
displayText: selector

price: 500
maxHp: 2000
mass: 10000
radius: 16

isPickableStartingUnit: true
overrideAndReplace: commandCenter

isBuilding: true

#спавнит юнита заменяющего строитель и умирающего
[attachment_turret]
x: 0
y: 0 
isUnselectable: true 
onCreateSpawnUnitOf: remove_starts_builder 

[action_RAI]
text: RAI
# iconImage:
convertTo: RAI_main_base
buildSpeed: 6s
#спавним юнита коий проигрывает анимцию создания шаба
whenBuilding_temporarilyConvertTo: building_RAIcommandCenter 

#[action_vanil]
#text: ванила
# iconImage:
#convertTo: commandCenter_fake
#buildSpeed: 6s
#whenBuilding_temporarilyConvertTo: building_commandCenter
 
[graphics]
image: selector.png

[movement]
movementType: NONE

[attack]
canAttack:false
