[core]
name: PVO_turret_T2
displayText: Air defense turret T2
displayText_ru: Т2 ПВО турель

class: CustomUnitMetadata
price: 1300
maxHp: 1000
mass: 1000

#used for placement, and placement of other buildings
constructionFootprint: -1, -1, 1, 1

techLevel: 1
buildSpeed: 17s

radius: 18
isBio: true

isBuilding: true

tags: T1turret

energyMax: 7
energyRegen: 0.01
energyNeedsToRechargeToFull: true

[graphics]
image: ROOT:buildings/turret/base/turret_base.png
image_wreak: ROOT:buildings/turret/base/ahahah_sdohla.png

[turret_0]
x:0
y:5

image_drawOffsetX: 0
image_drawOffsetY: 0

image: turret.png
canAttack: false 

[turret_1]
x:0
y:5

barrelX: -4
barrelY: 6

projectile: 1
resourceUsage: energy = 1
canAttackCondition: if self.resource.energy > 1 and self.resource.energy < 2

[turret_2]
x:0
y:5

barrelX: -2
barrelY: 6

projectile: 1
resourceUsage: energy = 1
canAttackCondition: if self.resource.energy > 2 and self.resource.energy < 3

[turret_3]
x:0
y:5

barrelX: 0
barrelY: 6

projectile: 1
resourceUsage: energy = 1
canAttackCondition: if self.resource.energy > 3 and self.resource.energy < 4

[turret_4]
x:0
y:5

barrelX: 2
barrelY: 6

projectile: 1
resourceUsage: energy = 1
canAttackCondition: if self.resource.energy > 4 and self.resource.energy < 5

[turret_5]
x:0
y:5

barrelX: 4
barrelY: 6

projectile: 1
resourceUsage: energy = 1
canAttackCondition: if self.resource.energy > 5 and self.resource.energy < 6

[turret_6]
x:0
y:5

barrelX: 4
barrelY: 4

projectile: 1
resourceUsage: energy = 1
canAttackCondition: if self.resource.energy > 6 and self.resource.energy < 7

[turret_7]
x:0
y:5

barrelX: 4
barrelY: 4

projectile: 1
resourceUsage: energy = 1
canAttackCondition: if self.resource.energy == 7

[projectile_1]
directDamage: 45
life: 240
speed: 0.8
targetSpeed: 7 
trailEffectRate: 3
largeHitEffect: true
#ballistic: true
#ballistic_delaymove_height:0
#ballistic_height: 4
frame: 4

autoTargetingOnDeadTarget: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretTurnSpeed: 2

maxAttackRange: 330

shootDelay: 50


[movement]
movementType: NONE
moveSpeed: 0

[ai]
buildPriority: 0.47
noneInBaseExtraPriority: 0.35

recommendedInEachBaseNum: 2
maxEachBase: 4
recommendedInEachBasePriorityIfUnmet: 0.7