[core]
name: T1_mech_factory

displayText:Т1 мех. завод
displayDescription: Т1 завод хеанизированой шагательной техники

price: 800
class: CustomUnitMetadata
maxHp: 700
mass: 9000
radius: 36

isBuilding: true

techLevel: 1
buildSpeed: 18s

exit_x: 0
exit_y: 25

#footprint used for collisions with units (left, up, right, down)
footprint: -1, -1, 1, 1

#used for placement, and placement of other buildings
constructionFootprint: -1,-1,1,1

canBuild_1_name: setRally
canBuild_1_pos:  -1 

[canBuild_T1]
pos:1
name: строитель_доходяга, boec, PVO_mech

[action_upgrade_T2] 
convertTo: T2factory
iconImage: ROOT:icons/improve.png
displayType: Upgrade
price: 1000
buildSpeed: 20s
text: Т2
description: Позволяет создавать юнитов второго класса.
pos: -1

isLocked: true
isVisible: if not self.tags(includes="T2Factory")  
#isLocked: if self.tags(includes="T2Factory")

# авто активация для ИИ когда у него досаточно денег (с запасом)
[hiddenAction_upgrade_T2_AI]
autoTriggerOnEvent: completeAndActive
requireConditional: if self.hasResources(credits=4000) and self.isControlledByAI and not self.tags(includes="T2Factory")  
alsoQueueAction: upgrade_T2

[graphics]
image_shadow: AUTO
image: T1_mech_factory.png
image_wreak: dead_T1_mech_factory.png

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
moveSlidingMode :false
moveIgnoringBody:false


[ai]
buildPriority: 0.7
ai_upgradePriority: 0.7
noneInBaseExtraPriority: 0.08
noneGlobalExtraPriority: 0.1
maxEachBase: 1
maxGlobal: 4