[core]
name: laser_turret
displayText: laser turret
displayText_ru: Лучевая турель
displayDescription: пробуждаеться по мере стрельбы и увеличивает урон

class: CustomUnitMetadata
price: 1000
maxHp: 900
mass: 1000

#used for placement, and placement of other buildings
constructionFootprint: -1, -1, 1, 1

techLevel: 1
buildSpeed: 17s

radius: 18
isBio: true

isBuilding: true

tags: T1turret

energyMax: 100
energyRegen: 0.2
energyNeedsToRechargeToFull: true

[graphics]
image_shadow: AUTO 
image_wreak: ROOT:buildings/turret/base/ahahah_sdohla.png
image: ROOT:buildings/turret/base/turret_base.png

[turret_0]
image: turret_not_active.png
x:0
y:0
aimOffsetSpread: 0
projectile: null_projectile

[turret_1]
x:0
y:0
attachedTo: 0

shoot_flame: fire
aimOffsetSpread: 0

projectile: laser1
canAttackCondition: if self.resource.ammo >= 1 and self.resource.energy <= 100 and self.resource.energy > 60
resourceUsage: energy = 1

[turret_2]
x:0
y:0
attachedTo: 0

shoot_flame: fire
aimOffsetSpread: 0

projectile: laser2
canAttackCondition: if self.resource.ammo >= 1 and self.resource.energy <= 60 and self.resource.energy > 40
resourceUsage: energy = 1

[turret_3]
x:0
y:0
attachedTo: 0

shoot_flame: fire
aimOffsetSpread: 0

projectile: laser3
canAttackCondition: if self.resource.ammo >= 1 and self.resource.energy <= 40 and self.resource.energy > 1
resourceUsage: energy = 1

[turret_4]
x:0
y:0
attachedTo: 0

shoot_flame: fire
aimOffsetSpread: 0

projectile: laser4
canAttackCondition: if self.resource.ammo >= 1 and self.resource.energy > 0
resourceUsage: energy = 1

[hiddenAction_energy_logic]
autoTrigger: if self.resource.energy >= 100 and self.resource.ammo < 1
addResources: ammo = 1

[hiddenAction_ammo_logic]
autoTrigger: if self.resource.energy < 1 and self.resource.ammo >= 1
addResources: ammo = -1


[hiddenAction_anim1]
autoTrigger: if self.resource.energy > 75 and self.resource.energy < 100 and self.isAttacking()
convertTo: laser_turret1

[hiddenAction_anim2]
autoTrigger: if self.resource.energy >= 50 and self.resource.energy < 75 and self.isAttacking()
convertTo: laser_turret2

[hiddenAction_anim3]
autoTrigger: if self.resource.energy >= 25 and self.resource.energy < 50 and self.isAttacking()
convertTo: laser_turret3

[hiddenAction_anim4]
autoTrigger: if self.resource.energy > 0 and self.resource.energy < 25 and self.isAttacking()
convertTo: laser_turret4

[hiddenAction_anim0]
autoTrigger: if not self.isAttacking()
convertTo: laser_turret

[projectile_laser1]
life: 20
autoTargetingOnDeadTarget: true

beamImage: iazik.png
#beamImageEnd:
#beamImageStart:

instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

directDamage: 2

[projectile_laser2]
life: 20
autoTargetingOnDeadTarget: true

beamImage: iazik.png
instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

directDamage: 5

[projectile_laser3]
life: 20
autoTargetingOnDeadTarget: true

beamImage: iazik.png
instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

directDamage: 8

[projectile_laser4]
life: 20
autoTargetingOnDeadTarget: true

beamImage: iazik.png
instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

directDamage: 12


[effect_fire]
image: ROOT:effect/salp.png

dirOffset:180

xOffsetRelative: 0
yOffsetRelative: 0
fadeInTime: 1

alpha: 0.5
life: 5

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 2

maxAttackRange: 160

shootDelay: 1.5

[movement]
movementType: NONE
turnAcceleration: 0
moveSpeed: 0

[ai]
buildPriority: 0.47
maxEachBase: 4 