[core]
name: laser_turret_turret
displayText: laser turret
displayText_ru: Лучевая турель

class: CustomUnitMetadata
price: 0
maxHp: 1
mass: 1000
radius: 18

energyMax: 100 
energyRegen: 0.2
energyNeedsToRechargeToFull: true

showInEditor: false

[graphics]
total_frames: 4

image: turret.png 

lock_body_rotation_with_main_turret: true

[turret_0]
x:0
y:0
aimOffsetSpread: 0
projectile: null_projectile 

[turret_1]
x:0
y:0
attachedTo: 0

shoot_flame: fire
aimOffsetSpread: 0

projectile: laser1
canAttackCondition: if self.resource.ammo >= 1 and self.resource.energy <= 100 and self.resource.energy > 60
resourceUsage: energy = 1

[turret_2]
x:0
y:0
attachedTo: 0

shoot_flame: fire
aimOffsetSpread: 0

projectile: laser2
canAttackCondition: if self.resource.ammo >= 1 and self.resource.energy <= 60 and self.resource.energy > 40
resourceUsage: energy = 1

[turret_3]
x:0
y:0
attachedTo: 0

shoot_flame: fire
aimOffsetSpread: 0

projectile: laser3
canAttackCondition: if self.resource.ammo >= 1 and self.resource.energy <= 40 and self.resource.energy > 1
resourceUsage: energy = 1

[turret_4]
x:0
y:0
attachedTo: 0

shoot_flame: fire
aimOffsetSpread: 0

projectile: laser4
canAttackCondition: if self.resource.ammo >= 1 and self.resource.energy > 0
resourceUsage: energy = 1

[hiddenAction_energy_logic]
autoTrigger: if self.resource.energy >= 100 and self.resource.ammo < 1
addResources: ammo = 1

[hiddenAction_ammo_logic]
autoTrigger: if self.resource.energy <= 1 and self.resource.ammo >= 1
addResources: ammo = -1

# перепробывал много всякого и не работает :[

#[hiddenAction_anim1]
#autoTrigger: if self.resource.energy < 100 and self.resource.energy >= 70 and self.resource.ammo >= 1
#playAnimation: a1

#[hiddenAction_anim2]
#autoTrigger: if self.resource.energy < 70 and self.resource.energy >= 50 and self.resource.ammo >= 1
#playAnimation: a2

#[hiddenAction_anim3]
#autoTrigger: if self.resource.energy < 50 and self.resource.energy >= 30 and self.resource.ammo >= 1
#playAnimation: a3

#[hiddenAction_anim4]
#autoTrigger: if self.resource.energy < 30 and self.resource.energy >= 0 and self.resource.ammo >= 1
#playAnimation: a4

[hiddenAction_anim2]
autoTrigger: if self.resource.energy < 90 and self.resource.ammo >= 1
playAnimation: a2

[hiddenAction_anim3]
autoTrigger: if self.resource.energy < 70 and self.resource.ammo >= 1
playAnimation: a3

[hiddenAction_anim4]
autoTrigger: if self.resource.energy < 50 and self.resource.ammo >= 1
playAnimation: a4


[projectile_laser1]
life: 20
autoTargetingOnDeadTarget: true

beamImage: iazik.png
#beamImageEnd: 
#beamImageStart:

instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

directDamage: 2

[projectile_laser2]
life: 20
autoTargetingOnDeadTarget: true

beamImage: iazik.png
instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

directDamage: 5

[projectile_laser3]
life: 20
autoTargetingOnDeadTarget: true

beamImage: iazik.png
instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

directDamage: 8

[projectile_laser4]
life: 20
autoTargetingOnDeadTarget: true

beamImage: iazik.png
instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

directDamage: 12


[animation_a1]
body_0s:{frame:0}
body_0.1s:{frame:0}
body_0.2s:{frame:0}
body_0.3s:{frame:0}
body_0.4s:{frame:0}
body_0.5s:{frame:0}
body_0.6s:{frame:0}
body_0.7s:{frame:0}
body_0.8s:{frame:0}


[animation_a2]
body_0s:{frame:1}
body_0.1s:{frame:1}
body_0.2s:{frame:1}
body_0.3s:{frame:1}
body_0.4s:{frame:1}
body_0.5s:{frame:1}
body_0.6s:{frame:1}
body_0.7s:{frame:1}
body_0.8s:{frame:1}
body_0.9s:{frame:1}
body_1.0s:{frame:1}


[animation_a3]
body_0s:{frame:2}
body_0.1s:{frame:2}
body_0.2s:{frame:2}
body_0.3s:{frame:2}
body_0.4s:{frame:2}
body_0.5s:{frame:2}
body_0.6s:{frame:2}
body_0.7s:{frame:2}
body_0.8s:{frame:2}
body_0.9s:{frame:2}
body_1.0s:{frame:2}

[animation_a4]
body_0s:{frame:3}
body_0.1s:{frame:3}
body_0.2s:{frame:3}
body_0.3s:{frame:3}
body_0.4s:{frame:3}
body_0.5s:{frame:3}
body_0.6s:{frame:3}
body_0.7s:{frame:3}
body_0.8s:{frame:3}
body_0.9s:{frame:3}
body_1.0s:{frame:3}


[effect_fire]
image: ROOT:effect/salp.png

dirOffset:180

xOffsetRelative: 0
yOffsetRelative: 0
fadeInTime: 1

alpha: 0.5
life: 5

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 2

maxAttackRange: 160

shootDelay: 1.5

[movement]
movementType: NONE
turnAcceleration: 0.1
moveSpeed: 0
