[core]
name: вирус_танк
displayText: вирусный танк

showInEditor: true
class: CustomUnitMetadata
price: 2000
maxHp: 1100
mass: 10000
transportSlotsNeeded: 2

techLevel: 2
buildSpeed: 15s

radius: 15
displayRadius: 16

energyMax: 10
energyRegen: 0.03
energyNeedsToRechargeToFull: true
isBio: true

[graphics]
total_frames: 3

image: body.png
image_wreak: dead_body.png
#image_turret: bashna.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 2

dustEffect: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 21
turretTurnSpeed: 3

maxAttackRange: 140
shootDelay: 25

# 1 орудие 
[turret_1]
#barrel
x: 0
y: 0
attachedTo: 2
slave: true
projectile: 1
turnSpeed: 0
image: turret.png

delay:15

barrelX: 4
barrelY: 17

turnSpeedAcceleration: 1.0

shoot_sound:gun_fire
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC

canShoot: true

energyUsage: 1
recoilOffset: 1
[turret_2]
#turret
x: 0
y: 0

recoilOffset: -1
recoilOutTime: 2
recoilReturnTime: 5

canShoot: false

[turret_3]
#barrel
x: 0
y: 0
attachedTo: 4
slave: true
projectile: 1
turnSpeed: 0
image: turret.png

barrelX: -2
barrelY: 17
linkDelayWithTurret: 1 
turnSpeedAcceleration: 1.0

shoot_sound:gun_fire
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC

canShoot: true

energyUsage: 1
recoilOffset: 1

[turret_4]
#turret
x: 0
y: 0

recoilOffset: -1
recoilOutTime: 2
recoilReturnTime: 5

canShoot: false
linkDelayWithTurret: 1 

[projectile_1]
directDamage: 25
life: 60
speed: 5
frame: 2

drawSize: 0.85

[movement]
movementType: LAND
moveSpeed: 0.9
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

reverseSpeedPercentage: 0.5

maxTurnSpeed: 5
turnAcceleration: 0.25

moveSlidingMode :false
moveIgnoringBody:false