[core]
name: goo

displayText: goo
displayDescription: I gooned yesterday
isUnselectable: true
showInEditor: false
disableAllUnitCollisions: true
canNotBeDamaged: true
price: 1
maxHp: 1
mass: 1
radius:80


[graphics]
image: goo.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[hiddenAction_DIEFUCKER]
autoTrigger: if self.noUnitInTeam(withTag="Base")
#autoTriggerCheckRate:every8Frames
deleteSelf: true

[movement]
movementType: NONE