[core]
name: RAI_main_base
displayText: RAI base
displayDescription: RAI base

class: commandCenter
price: 25000
maxHp: 7000
mass: 9000
radius: 55
selfRegenRate: 0.02

isBio: true
isBuilding: true
buildSpeed: 25s

exit_x: 20
exit_y: 0
#exit_moveAwayAmount:50

generation_credits: 18
generation_delay: 20

#footprint used for collisions with units (left, up, right, down)
footprint: -1, -1, 2, 1

#used for placement, and placement of other buildings
constructionFootprint: -1, -2, 2, 1

isPickableStartingUnit: true
tags: Base

[canBuild_T1]
name: строитель_доходяга

# авто постойка строителя в начале игры что бы бот не тупил тыщу лет перед этим и не был полным попуском
[hiddenAction_ForcedBuilder]
autoTrigger: if numberOfUnitsInTeam(lessThan=2, withTag='builder', incompleteBuildings=true) and self.isControlledByAI()
alsoQueueAction: ForcedBuilderProduce
allowMultipleInQueue: false 

[hiddenAction_ForcedBuilderProduce]
allowMultipleInQueue: false 
produceUnits: строитель_доходяга
addResources: -500
buildSpeed: 8.3s
refundAllQueuedItems: true

[graphics]
image: BaseballSbluN.png

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[movement]
movementType: NONE

[hiddenAction_0]
autoTriggerOnEvent: created
addResources: maxfabricator=40


[attachment_goo]
x: 0
y: 0
rotateWithParent: true
onCreateSpawnUnitOf: goo
lockRotation: true
isUnselectable: true
canBeAttackedAndDamaged: false
setDrawLayerOnTop: true