[core]
name: RAI_main_base
displayText: RAI base
displayDescription: RAI base

class: commandCenter
price: 25000
maxHp: 7000
mass: 9000
radius: 100
selfRegenRate: 0.02

isBio: true
isBuilding: true
buildSpeed: 25s

exit_x: 20
exit_y: 0
#exit_moveAwayAmount:50
isBio: true

generation_credits: 18
generation_delay: 20

#footprint used for collisions with units (left, up, right, down)
footprint: -1, -1, 2, 1

isPickableStartingUnit: true

[canBuild_T1]
name: строитель_доходяга

[graphics]
image: BaseballSbluN.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
moveSlidingMode :false
moveIgnoringBody:false

[attachment_goo]

x=0
y=0
rotateWithParent: true
onCreateSpawnUnitOf: goo
lockRotation: true
isUnselectable: true
canBeAttackedAndDamaged: false
setDrawLayerOnTop: true
