[core]
name: big_sgugalica
displayText: большая жужалица
displayDescription: Имеет 2 режима:\n огнемет и лазер. Лазеры наносят много урона и имеют довольно долгую перезарядку, а огнемет бьет по области и эффективен против спама.\n Имеет очень слабое самовосстановление.

showInEditor: true
class: CustomUnitMetadata
price: 8000
maxHp: 4000
mass: 5000

techLevel: 3
buildSpeed: 35s

radius: 15
displayRadius: 30

isBio: true

experimental: true

selfRegenRate: 0.007

[graphics]
image_shadow: AUTO
image: body.png 

movementEffect: move
movementEffectReverse: NONE
movementEffectRate: 1

lock_body_rotation_with_main_turret: true

[action_laser_mode]
text: лазерная стрельба

setResourcesWithLogic: mode = 1

[action_flamethower_mode]
text: огнемет

setResourcesWithLogic: mode = 2

[turret_laser_1]
x:0
y:0

canAttackCondition: if self.resource.mode == 1

projectile: laser
shoot_flame: laser_fire

shoot_sound: ROOT:sound_effect/laser_fire.ogg

warmup: 50
aimOffsetSpread: 0

barrelX: 9
barrelY: 30

[turret_laser_2]
copyFrom: laser_1
x:0
y:0

canAttackCondition: if self.resource.mode == 1

barrelX: -9
barrelY: 30

[turret_flamethower_1]
x:0
y:0

canAttackCondition: if self.resource.mode == 2
delay: 4
projectile: flamethower
aimOffsetSpread: 0.1

barrelX: 9
barrelY: 30

[turret_flamethower_2]
copyFrom: flamethower_1
x:0
y:0

canAttackCondition: if self.resource.mode == 2

barrelX: -9
barrelY: 30

[effect_laser_fire]
image: ROOT:effect/laser_fire_effect.png

fadeInTime: 2
alpha: 1.6

life: 22

[projectile_laser]
directDamage: 300
life: 13
autoTargetingOnDeadTarget: true

armourIgnoreAmount: 35

beamImage: ROOT:effect/laser.png
#beamImageEnd: 
#beamImageStart:

instant: true
largeHitEffect: true
#explodeEffect:
#explodeEffectOnShield:

#instantReuseLast: true
#instantReuseLast_alsoChangeTurretAim: true
explodeOnEndOfLife: true
beamImageOffsetRate: 4
drawSize: 0.5
#moveWithParent: true

sweepOffset: 1
sweepOffsetFromTargetRadius: 0.15
sweepSpeed: 1

[projectile_flamethower]
#flame thrower

life: 70
speed: 5.2
speedSpread: 1

frame: 3
drawSize: 1.2

flameWeapon: true
hitSound: false

targetGround:true
targetGroundSpread: 20

areaDamage: 2
areaRadius: 90

lightColor: #e23f0e
lightSize: 0.7

buildingDamageMultiplier: 0.7
shieldDamageMultiplier: 0.75

tags: inflictFire

[effect_move]
xOffsetRelative: 0
yOffsetRelative: -35

image: ROOT:effect/jet_stream_effect.png

total_frames: 4
animateFrameStart: 0 
animateFrameSpeed: 1 
animateFrameEnd: 3

fadeInTime: 4
alpha: 0.6
life: 30

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
maxAttackRange: 220
shootDelay: 100

[movement]
movementType: AIR
moveSpeed: 0.9
moveAccelerationSpeed: 2
moveDecelerationSpeed: 2
reverseSpeedPercentage: 0.3