[core]
name: remont_pulser
displayText: ремонтная станция

displayDescription: имеет 2 режима работы\n -в 1 ремотритует постройки и юнитов рементным лучем\n -во 2 испускает ремонтрирующие по облости пульсации

class: CustomUnitMetadata
price: 1500
maxHp: 950
mass: 1000

#used for placement, and placement of other buildings
constructionFootprint: 0, 0, 0, 0

techLevel: 1
buildSpeed: 17s

radius: 18
isBio: true

isBuilding: true

nanoRange: 255
nanoBuildSpeed: 1.5
nanoRepairSpeed: 0.3
canRepairBuildings: true
canRepairUnits: true
autoRepair: true

autoTriggerCooldownTime: 2s

[graphics]
image: body.png
image_shadow: AUTO

[action_radius_heal]
text: area heal 
text_ru: лечение пульсацией

autoTrigger: if self.isControlledByAI() and self.numberOfUnitsInTeam(greaterThan=12, withinRange=255)

iconImage: ROOT:icons/hilers.png
iconExtraImage: regen_radius.png

setResourcesWithLogic: ammo = 1
isVisible: if not self.self.isControlledByAI()

[action_nano_heal]
text: laser heal
text_ru: лечение лучем

autoTrigger: if self.isControlledByAI() and self.numberOfUnitsInTeam(lessThan=10, withinRange=255)

iconImage: ROOT:icons/hilers.png

setResourcesWithLogic: ammo = 2
isVisible: if not self.self.isControlledByAI()

[hiddenAction_radiusHeals]
buildSpeed: 0s
fireTurretXAtGround: heal
fireTurretXAtGround_withOffset: 0, 0
resetCustomTimer: true
canPlayerCancel: false

autoTrigger: if self.customTimer(laterThanSeconds=3) and self.resource.ammo == 1


[turret_heal]
# AREA HEAL TURRET
x: 0
y: 0

invisible: true
#limitingRange: 250

canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
projectile: radius_hil

turnSpeed: 5.0

shoot_sound:NONE
shoot_sound_vol:0.5
shoot_flame:NONE

canShoot: true
size: 0
delay: 0
warmup:0

canAttackCondition: if self.resource.ammo == 1

[turret_nano]
#nano turret
isMainNanoTurret: true 
x: 0
y: 14
barrelX: 0
barrelY: 0

canAttackCondition: if self.resource.ammo == 2

[projectile_radius_hil]
areaDamage: -15

areaDamageNoFalloff:true
areaRadius: 250
targetGround: true
areaExpandTime: 90
areaHitAirAndLandAtSameTime: true
speed: 0
life: 0
instant: false
largeHitEffect: true
explodeOnEndOfLife: true
deflectionPower: -1
shieldDamageMultiplier: 0
buildingDamageMultiplier: 0.5
friendlyFire: only-ignoreEnemy
explodeEffect: begraund_light, Healing

[effect_Healing]
priority:veryhigh
image: regen_radius.png
life: 30
fadeOut: true
attachedToUnit: true
color: #04920b
fadeInTime: 0
scaleFrom: 1
scaleTo: 4
alpha:  0.5
dirSpeedRandom: 30
drawUnderUnits: true

[effect_begraund_light]
image: SHARED:light_50.png
life: 50
fadeOut: true
fadeInTime: 1
attachedToUnit: true
color: #00c3ff
drawUnderUnits: false
scaleFrom: 0
scaleTo: 10.1
priority: low
alpha: 0.2
drawUnderUnits: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretTurnSpeed: 69

turretMultiTargeting: false
maxAttackRange: 255
shootDelay: 1s

[movement]
movementType: NONE