[core]
name: turret_T1
displayText: T1 turret 
displayText_ru: Т1 турель

class: CustomUnitMetadata
price: 550
maxHp: 700
mass: 1000

#used for placement, and placement of other buildings
constructionFootprint: -1, -1, 1, 1

techLevel: 1
buildSpeed: 17s

radius: 20
isBio: true

isBuilding: true

tags: T1turret

[graphics]
image: ROOT:buildings/turret/base/turret_base.png
image_wreak: ROOT:buildings/turret/base/ahahah_sdohla.png

[action_upgrade] 
convertTo: turret_T2
iconImage: ROOT:icons/improve.png
displayType: Upgrade
price: 900
buildSpeed: 20s
text: Т2 turret
description: Улучшает турель\n-появляеться 2 орудие\n-увеличиваеться: дальнобойность, обший урон, ХП
pos: -1

[turret_0]
x:0
y:5
canAttack: false
image:turret.png

[turret_1]
x:0
y:5
attachedTo: 0
slave: true

image_drawOffsetX: 0
image_drawOffsetY: 5

barrelX: 0
barrelY: 6

image: ROOT:buildings/turret/base/cannon.png

recoilOffset: -2
recoilOutTime: 5
recoilReturnTime: 5

[projectile_1]
directDamage: 35
life: 60
speed: 6.5
frame: 2

drawSize: 0.8

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretTurnSpeed: 2

maxAttackRange: 165

shootDelay: 65

[movement]
movementType: NONE
moveSpeed: 0

[ai]
buildPriority: 0.47
noneInBaseExtraPriority: 0.35

recommendedInEachBaseNum: 2
maxEachBase: 4
recommendedInEachBasePriorityIfUnmet: 0.7