[core]
name: experementalfactory

displayText:experemental factory
displayText_ru: эксп. завод 
displayDescription: завод производящий эксперементальную технику, дорогую но мощную

price: 5000
class: CustomUnitMetadata
maxHp: 2100
mass: 9000
radius: 53

isBuilding: true
buildSpeed: 28s

exit_x: 0
exit_y: 50
exit_moveAwayAmount: 100

#footprint used for collisions with units (left, up, right, down)
footprint: -2, -2, 2, 3

#used for placement, and placement of other buildings
constructionFootprint: -2,-2,2,4

canBuild_1_name: setRally
canBuild_1_pos:  1

[canBuild_exp]
name: строитель, big_sgugalica

[graphics]
total_frames: 1

image: top_layder.png
image_back: back.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1 
 
[arm_1]
x: 0
y: -52
image_end: vorota.png
drawOverBody: true

[arm_2]
x: 0
y: 0
image_end: top_layder.png
drawOverBody: true
image_end_teamColors: true

[animation_openDoor]
onActions: queuedUnits
onActionsQueuedUnitPlayAt: 0.8
blendIn: 2.2s 
blendOut: 2.2s 
arm1_0: {x:0, y:20}

[attack]
canAttack: false

[movement]
movementType: NONE

[ai]
buildPriority: 0.50
noneInBaseExtraPriority: 0.35

maxEachBase: 4
recommendedInEachBasePriorityIfUnmet: 0.5
