[core]
name: thunderhawk
displayText: Громовой Ястреб
displayDescription: Стремительный и неплохо бронированный транспортный самолет \n-имеет небольшую противовоздушную плазменную турель.
class: CustomUnitMetadata

price: 1700
mass: 10000 
maxHp: 875

radius: 20
displayRadius: 22

techLevel: 2
buildSpeed: 16s

isBio: true
transportSlotsNeeded: 5
maxTransportingUnits: 5

armour: 2

[graphics]
image: body.png
image_shadow: AUTO

movementEffect: move_big, move_small_l, move_small_r
movementEffectReverse: NONE
movementEffectRate: 1

dustEffect: false

[turret_1]
image: turret.png
x: 0
y: -16
projectile: 1
shoot_flame: fire
aimOffsetSpread: 0.01

barrelX: 3
barrelY: 14

[turret_2]
x: 0
y: 0
attachedTo: 1 
slave: true
aimOffsetSpread: 0.01

projectile: 1
shoot_flame: fire

barrelX: -3
barrelY: 14

[projectile_1]
directDamage: 30
frame: 8
life: 90
speed: 6
#trailEffectRate: 3

[effect_fire]
image: ROOT:effect/blue_lightning.png

life: 400
xOffsetRelative: 1
yOffsetRelative:-1 

total_frames: 3
animateFrameStart: 0 
animateFrameSpeed: 0.2
animateFrameEnd: 2

alpha: 0.9

[effect_move_big]
xOffsetRelative: 0
yOffsetRelative: -55
scaleTo: 1

image: ROOT:effect/jet_stream_effect.png

total_frames: 4
animateFrameStart: 0 
animateFrameSpeed: 1 
animateFrameEnd: 3

fadeInTime: 2
alpha: 0.5
life: 20

[effect_move_small_l]
xOffsetRelative: -16
yOffsetRelative: -40
scaleTo: 0.2

image: ROOT:effect/jet_stream_effect.png

total_frames: 4
animateFrameStart: 0 
animateFrameSpeed: 1 
animateFrameEnd: 3

fadeInTime: 2
alpha: 0.3
life: 15

[effect_move_small_r]
@copyFromSection: effect_move_small_l
xOffsetRelative: 16

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretTurnSpeed: 2.3
maxAttackRange: 170
shootDelay: 80

[movement]
movementType: AIR
moveSpeed: 2

landOnGround: true
moveAccelerationSpeed: 2
moveDecelerationSpeed: 2
reverseSpeedPercentage: 0.3

[ai] 
useAsTransport: true