[core]
name: main_base

displayText:база
displayDescription: база

price: 25000
class: commandCenter
maxHp: 7500
mass:9000
radius:80

isBio:true
isBuilding: true
buildSpeed:15s

exit_x: 20
exit_y: 0
#exit_moveAwayAmount:50

[canBuild_T1]
name: строитель_доходяга

[graphics]
image: BaseballSbluN.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
moveSlidingMode :false
moveIgnoringBody:false

[attachment_goo]

x=0
y=0
rotateWithParent: true
onCreateSpawnUnitOf: goo
lockRotation:true
isUnselectable:true
canBeAttackedAndDamaged: false
setDrawLayerOnTop: true
