[core]
name: строитель_доходяга
displayText: строитель
displayDescription: строитель

showInEditor: true
class: CustomUnitMetadata
price: 700
maxHp: 200
mass: 500

techLevel: 1
buildSpeed: 15s

canRepairBuildings: true
canRepairUnits : false

nanoRange: 70
nanoBuildSpeed: 0.4
nanoRepairSpeed: 0.3


tags: AiBuilder

radius: 20
displayRadius: 20

isBio: true

[graphics]
image: -строительRAI.png
#image_turret: турель.png

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[canBuild_Reclaim]
name: reclaim
pos:  -1

[canBuild_build]
forceNano: true
name: T1coc
pos:  1


[leg_1]
x: -8
y: 5
attach_x: -1
attach_y: 5
moveSpeed: 4

heightSpeed: 3
moveWarmUp: 2

resetAngle:10

holdDisMin_maxMovingLegs: 6 
holdDisMin: 1
holdDisMax: 2

image_leg: -строительRAI(leg).png
image_foot: -строительRAI(foot).png
estimatingPositionMultiplier: 0.6

[leg_2]
@copyFromSection: leg_1
x: 8
y: 5
attach_x: 1
attach_y: 5
estimatingPositionMultiplier: 0.5

[leg_3]
@copyFromSection: leg_1
x: -10
y: -10
attach_x: -1
attach_y: -5
estimatingPositionMultiplier: 0.5

[leg_4]
@copyFromSection: leg_1
x: 10
y: -10
attach_x: 3
attach_y: -6
estimatingPositionMultiplier: 0.5

#[leg_5] # ноги по середине
#@copyFromSection: leg_1
#x: 8
#y: -1
#attach_x: -25
#attach_y: -15
#estimatingPositionMultiplier: 0.5
#[leg_6]
#@copyFromSection: leg_1
#x: -11
#y: -1
#attach_x: 2
#attach_y: -6
#estimatingPositionMultiplier: 0.5


[movement]
movementType: OVER_CLIFF

moveSpeed: 1.2
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 3
turnAcceleration: 0.2

reverseSpeedPercentage: 1

moveSlidingMode :false
moveIgnoringBody:false