[core]
name: T2_air_defense
displayText: Т2 ПВО

showInEditor: true
class: CustomUnitMetadata
price: 2000
maxHp: 1100
mass: 2500
transportSlotsNeeded: 2

techLevel: 2
buildSpeed: 15s

radius: 17
displayRadius: 18

energyNeedsToRechargeToFull: true
isBio: true

[graphics]
total_frames: 2

image: body.png
image_wreak: dead_body.png
image_turret: T2_anti_air_flare_gun.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 2

dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
turretSize: 7

turretTurnSpeed: 3.5

maxAttackRange: 320
shootDelay: 30

[turret_1]
x: 0
y: 0
image: T2_anti_air_flare_gun.png

barrelX: 6
barrelY: 5

projectile: 1

shoot_sound: missile_fire
shoot_sound_vol: 0.3
shoot_flame: small
shoot_light: #FFEECCCC

recoilOffset: -0.2
recoilOutTime: 4
recoilReturnTime: 10

[turret_2]
x: 0
y: 0
copyFrom: 1 
attachedTo: 1

delay: 40
invisible: true
barrelX: -6
barrelY: 5

[projectile_1]
directDamage: 60
life: 250
speed: 0.5
targetSpeed: 6
trailEffectRate: 3
largeHitEffect: true
#ballistic: true
#ballistic_delaymove_height:0
#ballistic_height: 4
frame: 4

autoTargetingOnDeadTarget: true

[movement]
movementType: LAND
moveSpeed: 0.75
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

reverseSpeedPercentage: 0.6

maxTurnSpeed: 5
turnAcceleration: 0.25

moveSlidingMode :false
moveIgnoringBody:false