[core]
name: T1_mach_artillery_fine
displayText: mach artillery
displayText_ru: мех. артиллерия
displayDescription: Точная механизированная артиллерия

showInEditor: false
class: CustomUnitMetadata
price: 1100
maxHp: 650
mass: 2550

techLevel: 1
buildSpeed: 10s

radius: 15
displayRadius: 20

armour: 1

[graphics]
image_shadow: AUTO
image: body.png

# это нужно что бы скрипить турель 0 и создаль эффект отдачи не только пушки но и всего корпуса
lock_body_rotation_with_main_turret: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretTurnSpeed: 0
isFixedFiring: true

shootDelay: 2s

maxAttackRange: 280

[action_fine_mode]
text: обычный режим
description: Возврат в изначальный режим\n- меньше урона, больше радиус поражения\n- прежняя скорость
autoTrigger: if self.isControlledByAI() and (self.numberOfUnitsInEnemyTeam(withinRange=280) > 7 or self.numberOfUnitsInEnemyTeam(withinRange=100) > 3)

#playAnimation: action_leg
alsoQueueAction: convert
buildSpeed: 1s

[hiddenAction_convert]
unitShownInUIWithProgressBar: false
buildSpeed: 3s
convertTo: T1_mach_artillery

[arm_1]
x: 0
y: -1
image_end: ROOT:unit/mech/base/artilery_leg.png

[arm_2]
x: 0
y: -1
image_end: ROOT:unit/mech/base/artilery_leg.png

[animation_action_leg]
blendOut: 4s
arm1_0s:  {x:-24, y:-1, dir:90}
arm1_1s:  {x:-20, y:-1, dir:90}
arm1_1.5s:{x:-15, y:-1, dir:90}
arm1_2s:  {x:-10, y:-1, dir:90}
arm1_3s:  {x:-5,  y:-1, dir:90}
arm1_5s:  {x:0,   y:0,  dir:90}

arm2_0s:  {x:12, y:-1, dir:90}
arm2_1s:  {x:10, y:-1, dir:90}
arm2_1.5s:{x:5,  y:-1, dir:90}
arm2_2s:  {x:4,  y:-1, dir:90}
arm2_3s:  {x:3,  y:-1, dir:90}
arm2_5s:  {x:0,  y:0,  dir:90}

[turret_1]
x: 0
y: 0
image: ROOT:icons/nah_sprite.png

aimOffsetSpread: 0
delay: 2s
projectile: null_projectile

[turret_2]
x: -1
y: 10

attachedTo: 1
slave: true 

image: turret.png
aimOffsetSpread: 0
projectile: 1

shoot_sound: cannon_firing
shoot_sound_vol: 0.6

recoilOffset: -4
recoilOutTime: 4
recoilReturnTime: 10

[projectile_1]
areaDamage: 75
areaRadius: 40

image: ROOT:effect/arta_projectile.png

life: 80
speed: 3.85
frame: 2

drawSize: 0.65

[leg_1]
x: -19
y: 9
attach_x: -5
attach_y: 5
moveSpeed: 1.4

heightSpeed: 2
moveWarmUp: 6

resetAngle: 15
image_end_teamColors: true

holdDisMin_maxMovingLegs: 4
holdDisMin: 1
holdDisMax: 2.3
hardLimit: 16

dust_effect: true
image_leg: ROOT:unit/mech/base/artilery_leg.png
image_foot: ROOT:unit/mech/base/artilery_foot.png
estimatingPositionMultiplier: 0.55

[leg_2]
@copyFromSection: leg_1
x: 19
y: 9
attach_x: 5
attach_y: 5

[leg_3]
@copyFromSection: leg_1
moveWarmUp: 1
x: -18
y: -17
attach_x: -5
attach_y: -5

[leg_4]
@copyFromSection: leg_1
x: 18
y: -17
attach_x: 5
attach_y: -5

[leg_5]
@copyFromSection: leg_1
moveWarmUp: 1
x: 20
y: -5
attach_x: 0
attach_y: 1
estimatingPositionMultiplier: 0.5

[leg_6]
@copyFromSection: leg_1
moveWarmUp: 1
x: -20
y: -5
attach_x: 0
attach_y: 1
estimatingPositionMultiplier: 0.5

[movement]
movementType: OVER_CLIFF

moveSpeed: 0.4
moveAccelerationSpeed: 0.055
moveDecelerationSpeed: 0.12

maxTurnSpeed: 1
turnAcceleration: 0.15

reverseSpeedPercentage: 0.22

moveSlidingMode :false
moveIgnoringBody:false