[core]
name: T2_virus_tesla_tank_turret
displayText: вирусный тесла танк (турель)

showInEditor: false
class: CustomUnitMetadata
price: 1
maxHp: 1
mass: 1
transportSlotsNeeded: 0

techLevel: 1
buildSpeed: 00.1

radius: 11
displayRadius: 13

isBio: true

[graphics]
total_frames: 12

image: turret.png

image_shadow: AUTO
#animation_attack_start: 0
#animation_attack_end: 11
#animation_attack_speed: 5

shadowOffsetX:2
shadowOffsetY:2
lock_body_rotation_with_main_turret: true
splastEffect:true

[animation_charge]
#onActions: attack
body_0.1s: {frame: 0}
body_0.2s: {frame: 1}
body_0.3s: {frame: 3}
body_0.4s: {frame: 4}
body_0.5s: {frame: 5}
body_0.6s: {frame: 6}
body_0.7s: {frame: 7}

[animation_discharge]
onActions: attack
body_0.7s: {frame: 8}
body_0.8s: {frame: 9}
body_0.9s: {frame: 10}
body_1s: {frame: 11}

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true

turretSize: 20
turretTurnSpeed: 4

maxAttackRange: 180

shootDelay:120

[turret_0]
x: 0
y: 0
attachedTo: 2
slave: true

projectile: null 

onShoot_playAnimation: charge

[turret_1]
#coil
x: 0
y: 0
attachedTo: 2
slave: true

projectile: 1

turnSpeed: 0
turnSpeedAcceleration: 0

shoot_sound:lighting_burst
shoot_sound_vol:0.3
shoot_flame:CUSTOM:sparks2*3
shoot_light:#FFcceeee

#onShoot_playAnimation: discharge

canShoot: true

warmup: 25

warmupShootDelayTransfer: 4

#chargeEffectImage: SHARED:lighting_charge.png

recoilOffset: -1.5
recoilOutTime: 3
recoilReturnTime: 17


[turret_2]
#turret
x: 0
y: 0

canShoot: false

turnSpeed: 2.5
turnSpeedAcceleration: 0.18
turnSpeedDeceleration: 0.35

recoilOffset: -0.75
recoilOutTime: 3
recoilReturnTime: 17

[projectile_1]
directDamage: 155

life: 25
instant: true
lightingEffect: true
largeHitEffect: true

shieldDamageMultiplier: 1
shieldDefectionMultiplier: 0.1
buildingDamageMultiplier: 0.5

explodeEffect:CUSTOM:lightningShock, CUSTOM:sparks*8
explodeEffectOnShield:CUSTOM:lightningShock*1, CUSTOM:hitLightFlash

[projectile_null]
directDamage:0
life: 80
image: ROOT:icons/nah_projectile.png
trailEffect: false
explodeEffect: null

[effect_hitLightFlash]
priority:high

image: SHARED:light_50.png

life: 17
fadeOut: true
attachedToUnit: false
color: #63e6e8

scaleFrom: 1.8
scaleTo: 1.8
alpha: 0.6
drawUnderUnits:false


[effect_null]
image: ROOT:icons/nah_projectile.png

[effect_lightningShock]
life: 60

hOffset: 0
dirOffset: 0

fadeInTime: 0
fadeOut: false

attachedToUnit: true

image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5

[effect_sparks]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 1.6
ySpeedRelativeRandom: 1.6
hSpeed: 2
image: SHARED:spark.png
priority: verylow

[effect_sparks2]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: SHARED:spark.png
priority: verylow

[movement]
movementType: NONE
moveSpeed: 0