[core]
name: блитскриг_танк
displayText: Блитскриг
displayDescription: наступательный танк "Блитскриг"

showInEditor: true
class: CustomUnitMetadata
price: 980
maxHp: 700
mass: 2000
transportSlotsNeeded: 1

techLevel: 1
buildSpeed: 8s

radius: 10 
displayRadius: 10

energyMax: 4
energyRegen: 0.022
energyNeedsToRechargeToFull: true

[graphics]
total_frames: 4

image: body.png
image_wreak: dead_body.png
#image_turret: bashna.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 3
animation_moving_speed: 2

dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 7
turretTurnSpeed: 4

maxAttackRange: 130
shootDelay: 10

[turret_1]
#barrel
x: 0
y: 0
attachedTo: 2
slave: true

projectile: 1

turnSpeed: 0

image: bashna.png

turnSpeedAcceleration: 1.0

shoot_sound:gun_fire
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC

canShoot: true

energyUsage: 1
recoilOffset: 1

[turret_2]
#turret
x: 0
y: 0

recoilOffset: -1
recoilOutTime: 3
recoilReturnTime: 6

canShoot: false

[projectile_1]
directDamage: 15
life: 60
speed: 6
frame: 1

drawSize: 0.8


[movement]
movementType: LAND
moveSpeed: 1.2
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

reverseSpeedPercentage: 0.75

maxTurnSpeed: 5
turnAcceleration: 0.25

moveSlidingMode :false
moveIgnoringBody:false