[core]
name: selector
displayText_ru: Селектор
displayText: selector

class: commandCenter
price: 500
maxHp: 2000
mass: 10000
radius: 16

isPickableStartingUnit: true
overrideAndReplace: commandCenter

isBuilding: true

tags: selector

energyMax: 1000 
energyRegen: 5

autoTriggerCooldownTime: 1s

[canBuild_0]
name: строитель_доходяга
isVisible: false

#---------------------------
# индификатор(флаг) RAI(синих жуков): 1
# индификатор(флаг) NEW(людей): 2
#---------------------------

[action_RAI]
# задаем индекс определяющий фракцию как индификатор для шаблонной логики
@define fraction_index: 1
buildSpeed: 0s
showMessageToAllPlayers: %{self.playerName} Chose a faction
showMessageToAllPlayers_ru: %{self.playerName} Выбрал фракцию
resetCustomTimer: true

# мерцающая обводка
isGuiBlinking: if self.hasFlag(id=${fraction_index})
isLocked: if self.hasFlag(id=${fraction_index})
# для нажатия 1 раз
allowMultipleInQueue: false
alwaysSinglePress: true

# добовляем тег-маркер готовности
temporarilyAddTags: ready

# активриуем флаг согласно индификатору для понимания какая фракция выбрана
addResources: setFlag=${fraction_index}

text: RAI
iconImage: bases/RAi_base/GBaseballShadow.png

[action_NEW]
@define fraction_index: 2
buildSpeed: 0s
showMessageToAllPlayers: %{self.playerName} Chose a faction
showMessageToAllPlayers_ru: %{self.playerName} Выбрал фракцию
resetCustomTimer: true

# мерцающая обводка
isGuiBlinking: if self.hasFlag(id=${fraction_index})
isLocked: if self.hasFlag(id=${fraction_index})
# для нажатия 1 раз
allowMultipleInQueue: false
alwaysSinglePress: true

description: "NEW"\n N - new\n E - ensecured\n W - world
description_ru: NEW\n N - new (новый)\n E - ensecured (защищённый)\n W - world (мир)

# добовляем тег-маркер готовности
temporarilyAddTags: ready

# активриуем флаг согласно индификатору для понимания какая фракция выбрана
addResources: setFlag=${fraction_index}

text: "NEW"
text_ru: NEW
iconImage: bases/NEW_base/NEW_base.png

[action_cancel]
text: cancel
text_ru: отмена

# or int(self.customTimer()) == 5 нужно что бы предотвратить баг с не сроьатыванием кнопки отмены в последнюю секунду из за задержки обновления hiddenAction_rest_timer (это коло раз в 0.7 сек)
isLocked: if (not self.hasFlag(id=1) and not self.hasFlag(id=2)) or int(self.customTimer()) == 5
isLockedAltMessage: нужно выбрать фракцию\nотменять пока не чего

showMessageToAllPlayers: %{self.playerName} canceled the choice of faction
showMessageToAllPlayers_ru: %{self.playerName} отменил выбор
ai_isDisabled: true

# убираем тег-маркер для того что бы покозать что кто то не готов
temporarilyRemoveTags: ready

buildSpeed: 0
# выключаем флаг выбраной фракции и сбрасываем 25 флаг
addResources: unsetFlag=1, unsetFlag=2 

resetCustomTimer: true

[hiddenAction_convert_to_RAI]
autoTrigger: if self.hasFlag(id=1) and self.customTimer() > 6 and numberOfUnitsInAllTeams(withTag="selector") == numberOfUnitsInAllTeams(withTag="ready")

showMessageToPlayer: В бой !

convertTo: RAI_main_base
#whenBuilding_temporarilyConvertTo: RAI_main_base
spawnUnits: goo
attachments_addNewUnits: goo

[hiddenAction_convert_to_human_base]
autoTrigger: if self.hasFlag(id=2) and self.customTimer() > 6 and numberOfUnitsInAllTeams(withTag="selector") == numberOfUnitsInAllTeams(withTag="ready")
showMessageToPlayer: В бой !

convertTo: NEW_main_base

# обратный отсчет
[hiddenAction_starts]
autoTrigger: if self.customTimer() > 0 and (self.hasFlag(id=1) or self.hasFlag(id=2)) and self.customTimer() <= 6 and numberOfUnitsInAllTeams(withTag="selector") == numberOfUnitsInAllTeams(withTag="ready")

showMessageToPlayer: %{int(self.customTimer())}

# сбрасываем таймер для синхронищации отсчета вообе у всех
[hiddenAction_rest_timer]
autoTrigger: if numberOfUnitsInAllTeams(withTag="selector") != numberOfUnitsInAllTeams(withTag="ready")
resetCustomTimer: true

# выбор случайной фракции с более "случайным" рандомом
[hiddenAction_true_random]
autoTriggerOnEvent: created
setUnitStats: maxEnergy = self.x()

@global random_num: int(((int(rnd(1, self.y())) - 1) / (self.y() - 1) + 1) + 0.5)

[hiddenAction_random_RAI]
# новое_значение = ((старое_значение - старый_мин) * новый_диапазон) / старый_диапазон + новый_мин + 0.5(округление)            
autoTrigger: if ${random_num} == 1 and self.isControlledByAI() and (not self.hasFlag(id=1) and not self.hasFlag(id=2)) 
alsoQueueAction: RAI

[hiddenAction_random_human]
autoTrigger: if ${random_num} == 2 and self.isControlledByAI() and (not self.hasFlag(id=1) and not self.hasFlag(id=2))
showMessageToPlayer: рандом решил... "NEW"!
alsoQueueAction: NEW

[graphics]
image: selector.png
showEnergyBar: false

image_offsetY: -10
image_offsetX: 1

[movement]
movementType: NONE

[attack]
canAttack:false
