[core]
name: fake_builder
displayText: Builder
displayText_ru: Строитель
displayDescription: -строит и ремонтирует здания\n-не может атаковать

showInEditor: true
class: CustomUnitMetadata
price: 500
maxHp: 170
mass: 1000

techLevel: 1
buildSpeed: 8.3s

canRepairBuildings: true
canRepairUnits : false

nanoRange: 70
nanoBuildSpeed: 0.9
nanoRepairSpeed: 1

tags: builder

radius: 8
displayRadius: 11

overrideAndReplace: remove_starts_builder

[graphics]
image_shadow: AUTO
image: builder.png
image_wreak: builder_dead.png

lock_body_rotation_with_main_turret: true

[canBuild_Reclaim]
name: reclaim
pos:  -1

[canBuild_buildisgs]
name: extractorT1, c_turret_t1, c_antiAirTurret, landFactory, airFactory, seaFactory, mechFactory, laserDefence, repairbay, fabricatorT1, experimentalLandFactory, nukeLauncherC, antiNukeLauncherC

[turret_1]
x:0
y:1

#isMainNanoTurret: true
shoot_flame: build

canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false

[effect_build]
image: ROOT:effect/builder_charge.png

life: 100

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[movement]
movementType: LAND
moveSpeed: 0.80
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.09

reverseSpeedPercentage: 0.2

maxTurnSpeed: 2.5
turnAcceleration: 0.3

moveSlidingMode :false
moveIgnoringBody:false

[ai]
useAsBuilder: true
buildPriority: 0.6
noneInBaseExtraPriority: 0.4