[core]
name: NEW_main_base
displayText: "NEW" base
displayText_ru: База NEW 

displayDescription: "NEW"\n N - new\n E - ensecured\n W - world
displayDescription_ru: NEW\n N - new (новый)\n E - ensecured (защищённый)\n W - world (мир)

class: CustomUnitMetadata
price: 25000
maxHp: 7000
mass: 9000
radius: 45
selfRegenRate: 0.02

isBuilding: true
buildSpeed: 25s

fogOfWarSightRange: 25

exit_x: 10
exit_y: 15
#exit_moveAwayAmount:50

generation_credits: 18
generation_delay: 20

canBuild_1_name: setRally
canBuild_1_pos:  -1 

#footprint used for collisions with units (left, up, right, down)
footprint: -1, -1, 1, 1

isPickableStartingUnit: true
tags: Base

[canBuild_T1]
name: NEW_builder

# авто постойка строителя в начале игры что бы бот не тупил тыщу лет перед этим и не был полным попуском
[hiddenAction_ForcedBuilder]
autoTrigger: if numberOfUnitsInTeam(lessThan=2, withTag='builder', incompleteBuildings=true) and self.isControlledByAI() and self.resource.credits > 1000
alsoQueueAction: ForcedBuilderProduce
allowMultipleInQueue: false 

[hiddenAction_ForcedBuilderProduce]
allowMultipleInQueue: false 
produceUnits: NEW_builder
addResources: -500
buildSpeed: 8.3s
refundAllQueuedItems: true

[graphics]
image_shadow: AUTO
image: NEW_base.png

[hiddenAction_0]
autoTriggerOnEvent: created
addResources: maxfabricator=40

[attack]
canAttack: false

[movement]
movementType: NONE