[core]
name: строитель
displayText: Тех. строитель
displayDescription: -продвинутый строитель строитель\n-имеет малое само восстановление\n-может чинить юнитов

showInEditor: true
class: CustomUnitMetadata
price: 1900
maxHp: 1000
mass: 1000

techLevel: 2
buildSpeed: 15s

canRepairBuildings: true
canRepairUnits: true

nanoRange: 95
nanoBuildSpeed: 2.0
nanoRepairSpeed: 0.3

tags: builder

radius: 20
displayRadius: 21

isBio: true

selfRegenRate: 0.01

[graphics]
image_shadow: AUTO
image: body.png
image_turret: turret.png

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[canBuild_Reclaim]
name: reclaim
pos:  -1

[canBuild_extractor_build]
name: RAIextractor
pos:  1

#[canBuild_T1_cocon]
#name: T1coc, T2coc
#isLocked: if self.isControlledByAI
[canBuild_other]
name: fabricatorT1_m
pos: 3

[canBuild_build_logic_factory]
name: T1factory, T2factory
isLocked: if not numberOfUnitsInTeam(lessThan=55, withTag='T2Factory', incompleteBuildings=true) and self.isControlledByAI()
pos:  2

[turret_1]
#nano turret 
x: 2
y: 13

barrelX: 0
barrelY: 14

[effect_builds]
image: ROOT:effect/builder_charge.png

fadeInTime: 2
fadeOut: 1 

life: 300

[leg_1]
x: -8
y: 11
attach_x: -1
attach_y: 8
moveSpeed: 2.6

heightSpeed: 2
moveWarmUp: 3

resetAngle:10

holdDisMin_maxMovingLegs: 6 
holdDisMin: 1
holdDisMax: 2

image_leg: leg1.png
image_foot: foot.png
estimatingPositionMultiplier: 0.6

[leg_2]
@copyFromSection: leg_1
image_leg: leg2.png
x: 8
y: 11
attach_x: 1
attach_y: 8
estimatingPositionMultiplier: 0.6

[leg_3]
@copyFromSection: leg_1
x: -10
y: -10
attach_x: -1
attach_y: -5
estimatingPositionMultiplier: 0.6

[leg_4]
@copyFromSection: leg_1
x: 10
y: -10
attach_x: 3
attach_y: -6
estimatingPositionMultiplier: 0.6

[leg_5]
@copyFromSection: leg_1
image_leg: leg2.png
x: 8
y: -1
attach_x: -25
attach_y: -15

[leg_6]
@copyFromSection: leg_1
x: -11
y: -1
attach_x: 2
attach_y: -6


[movement]
movementType: OVER_CLIFF

moveSpeed: 0.65
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 3
turnAcceleration: 0.2

reverseSpeedPercentage: 0.5

moveSlidingMode :false
moveIgnoringBody:false

[ai]
useAsBuilder: true
maxGlobal: 6