[core]
name: T2factory

displayText:Т2 завод техники
displayDescription: Т2 завод наземной техники

price: 2000
class: CustomUnitMetadata
maxHp: 1100
mass: 9000
radius: 36

isBuilding: true

buildSpeed: 20s

exit_x:0
exit_y:20

#footprint used for collisions with units (left, up, right, down)
footprint: -1, -1, 1, 1

canBuild_1_name: setRally
canBuild_1_pos:  1

[canBuild_T1]
name: строитель_доходяга, air_defense, блитскриг_танк, virus_flamethower, легкий_танк  

[canBuild_T2]
name: строитель, жук, T2_air_defense, virus_artelery, вирус_танк, T2_virus_tesla_tank

#[action_upgrade] 
#convertTo: 
#iconImage: ROOT:icons/улучшение_кокона.png
#displayType: Upgrade
#price: 1000
#buildSpeed: 20s
#text: Т2
#description: Позволяет создавать юнитов второго класса.
#pos: -1

[graphics]
image: T2_factory.png

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
moveSlidingMode :false
moveIgnoringBody:false

[ai]
buildPriority: 0.8
ai_upgradePriority: 0.6
noneInBaseExtraPriority: 0.21
recommendedInEachBasePriorityIfUnmet: 0.8
noneGlobalExtraPriority: 0.4
maxEachBase: 3
maxGlobal: 20

# не даст ИИ активырывать пока у него не появиься достаточно денег (с запасом)
#[hiddenAction_upgradeAI]
#autoTriggerOnEvent:completeAndActive
#requireConditional:if self.hasResources(credits=2500) and self.isControlledByAI
#alsoQueueAction:upgrade