[core]
name: oreshnik
displayText: орешник

showInEditor: true
class: CustomUnitMetadata
price: 3000
maxHp: 850
mass: 9000
transportSlotsNeeded: 2

techLevel: 2
buildSpeed: 20s

radius: 19
displayRadius: 22

energyMax: 4
energyRegen: 0.005
energyNeedsToRechargeToFull: true

isBio: true

[graphics]
total_frames: 3

image: body.png
#image_wreak: dead_body.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 2.5

dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

#turretSize: 21
turretTurnSpeed: 1.8

maxAttackRange: 310
shootDelay: 200

[turret_0]
x:0
y:0
image: turret.png
canAttack: false

[turret_1]
x:0
y:0
barrelX: 5
barrelY: 0
image: roket2.png 
projectile: 1

attachedTo: 0
slave: true
warmup: 15
shoot_flame: smog

canAttackCondition: if self.resource.energy >= 4 and self.resource.ammo < 4 
invisible: if self.resource.energy < 4
resourceUsage: energy = 1, ammo = -5

[turret_2]
x:0
y:0
barrelX: 0
barrelY: 0
image: roket1.png 
projectile: 1

attachedTo: 0
slave: true
warmup: 15
shoot_flame: smog

canAttackCondition: if (self.resource.energy >= 3 and self.resource.ammo >= 4) or (self.resource.ammo >= 3 and self.resource.ammo >= 3)
invisible: if self.resource.energy < 3
resourceUsage: energy = 1, ammo = 1

[turret_3]
x:0
y:0
barrelX: -10
barrelY: 0
image: roket3.png 
projectile: 1

attachedTo: 0
slave: true
warmup: 15
shoot_flame: smog

canAttackCondition:  if (self.resource.energy >= 2 and self.resource.ammo >= 4) or (self.resource.ammo >= 3 and self.resource.ammo >= 2)
invisible: if self.resource.energy < 2
resourceUsage: energy = 1, ammo = 1

[turret_4]
x:0
y:0
barrelX: -15
barrelY: 0
image: roket4.png 
projectile: 1

attachedTo: 0
slave: true
warmup: 15
shoot_flame: smog

canAttackCondition: if (self.resource.energy >= 1 and self.resource.ammo >= 4) or (self.resource.ammo >= 3 and self.resource.ammo >= 1)
invisible: if self.resource.energy < 1
resourceUsage: energy = 1, ammo = 1

[projectile_1]
areaDamage: 185
areaRadius: 35

image: roket1.png
life: 500
speed: 0.5
targetSpeed: 3
targetSpeedAcceleration: 0.05
armourIgnoreAmount: 25
deflectionPower: 3
autoTargetingOnDeadTarget: true

trailEffect: roket_flame

[effect_smog]
image: ROOT:/effect/smog.png
life: 100

xOffsetRelative: 0
yOffsetRelative: -5

total_frames: 5
animateFrameStart: 0 
animateFrameSpeed: 0.2
animateFrameEnd: 4

[effect_roket_flame]
image: ROOT:/effect/miniature_roket_fire_8_frme.png

xOffsetRelative: 5
yOffsetRelative: -9

life: 100

total_frames: 8
animateFrameStart: 0 
animateFrameSpeed: 1
animateFrameEnd: 7

[movement]
movementType: LAND
moveSpeed: 0.5
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.10

reverseSpeedPercentage: 0.4

maxTurnSpeed: 4
turnAcceleration: 0.3

moveSlidingMode :false
moveIgnoringBody:false
