[core]
name: virus_radar
displayText: радар
displayDescription: ничто не утаить от моего взора !

showInEditor: true
class: CustomUnitMetadata
price: 1550
maxHp: 900
mass: 5000
transportSlotsNeeded: 2

techLevel: 2
buildSpeed: 18s

radius: 18
displayRadius: 19

fogOfWarSightRange: 32

isBio: true

[graphics]
total_frames: 3

image: body.png

image_shadow: AUTO
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 2

dustEffect: true

[turret_1]
x:0
y:0

image: turret.png

idleSpin: 1
#idleSweepAngle: 360 

[attack]
canAttack: false

[movement]
movementType: LAND
moveSpeed: 0.7
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

reverseSpeedPercentage: 0.45

maxTurnSpeed: 4
turnAcceleration: 0.3

moveSlidingMode :false
moveIgnoringBody:false