[core]
name: T1coc

displayText:Т1 кокан
displayDescription: кукан

price: 1000
class: CustomUnitMetadata
maxHp: 700
mass:9000
radius:30

isBio:true
isBuilding: true

buildSpeed:15s

exit_x:0
exit_y:-1
exit_moveAwayAmount:35

[canBuild_T1]
name: строитель_доходяга
addResources: hp = -701
    
#[action_Upgrade2]
#convertTo: T2coc
#iconImage: ROOT:icons/улучшение_кокона.png
#displayType: Upgrade
#price: 1000
#buildSpeed: 20s
#text: Т2
#description: Позволяет создавать юнитов второго класса.
#pos: -1

[graphics]
image: -коконТ1.png

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
moveSlidingMode :false
moveIgnoringBody:false